### PR TITLE
[CELEBORN-1708] Bump protobuf version from 3.21.7 to 3.25.5

### PR DESCRIPTION
**Pull request by turboFei**
### What changes were proposed in this pull request?

Bump protobuf from 3.21.7 to 3.25.5.

### Why are the changes needed?

To fix CVE: https://github.com/advisories/GHSA-735f-pc8j-v9w8

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?

GA.

### CODE REVIEW

**Comment by pan3793** [comment]
the recent protobuf java versions introduced "runtime jar version" and "generated code version" check, it may affect the case: if we pull a thrid-party dependency that contains the generated protobuf code, we should be careful on bumping protobuf runtime jars version. For the Celeborn case, please also test Ratis gRPC mode when bumping protobuf versions.

**Comment by turboFei** [comment]
@pan3793 how about adding the UT with grpc mode?

The protobuf is shaded and the shaded.protobuf.version is 3.24.4 in ratis 3.1.1 and 3.1.2.

**Comment by pan3793** [comment]
it should has no issue if ratis uses a shaded protobuf

**Review by pan3793 — APPROVED** [review]
lgtm if CI green

**Review by FMX — APPROVED** [review]
LGTM. Thanks. Merged into main(v0.6.0).

**Pull request closed without merging**
