### PR TITLE
[CELEBORN-1745] Fix application top disk usage

### PR DESCRIPTION
**Pull request by turboFei**
### What changes were proposed in this pull request?

In this PR, we calculate all the worker app disk usage as the application disk usage.

1. rename the AppDiskUsageMetric -> AppDiskUsageMetricManager and move into master module
2. record the appDiskUsage map in WorkerInfo, the memory pressure should be fine.
3. update the app usage metrics periodically.
    - loop the applicationIds 
    - aggregate the worker app disk usage as the app disk usage.

### Why are the changes needed?
The currently application top disk usage calculation is not correct, it uses the single worker app disk usage to update the metric, and it also always change and make it confused. 

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

GA.

### CODE REVIEW

**Comment by FMX** [comment]
Due to the application dimension resource consumption, this feature should be included in the deprecated features.  Maybe you can remove the codes for application top disk usage.
cc @RexXiong

**Comment by turboFei** [comment]
> Maybe you can remove the codes for application top disk usage.

Remove the code both in master and worker end? @FMX

**Comment by FMX** [comment]
Yes, it should be removed. Thanks.

**Comment by turboFei** [comment]
BTW, this prometheus expr does not work well.

```
topk(5, sum by (applicationId) (metrics_diskBytesWritten_Value{cluster="apollo", zone="rno", role="worker"}))
```

Because it does not reserve the `{{applicationId}}` label. 

Any suggestion? @FMX

**Pull request closed without merging**
