### PR TITLE
[CELEBORN-1521][FOLLOWUP] Using AuthenticationException instead of SecurityException

### PR DESCRIPTION
**Pull request by turboFei**
### What changes were proposed in this pull request?
As title.

### Why are the changes needed?
Have to use AuthenticationException to return status code 401 on auth failure, otherwise, it is `500`.
https://github.com/apache/celeborn/blob/9fefa66318e5c6e0f2237f63200ade8aba367e75/service/src/main/scala/org/apache/celeborn/server/common/http/authentication/AuthenticationFilter.scala#L159-L160

### Does this PR introduce _any_ user-facing change?
No, this interface has not been released.

### How was this patch tested?
Existing GA.

### CODE REVIEW

**Comment by turboFei** [comment]
cc @pan3793

**Comment by turboFei** [comment]
cc @pan3793

**Comment by turboFei** [comment]
gentle ping @pan3793

**Review by RexXiong — APPROVED** [review]
LGTM

**Pull request closed without merging**
