### PR TITLE
[CELEBORN-1516] DynamicConfigServiceFactory should support singleton.

### PR DESCRIPTION
**Pull request by leixm**
### What changes were proposed in this pull request?
DynamicConfigServiceFactory supports singleton.

### Why are the changes needed?
Improve code.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Existing UTs.

### CODE REVIEW

**Comment by leixm** [comment]
@RexXiong  PTAL.

**Review by AngersZhuuuu — APPROVED** [review]
LGTM

**Comment by RexXiong** [comment]
Thanks, could you create a jira ticket for this modify? @leixm

**Review by RexXiong — APPROVED** [review]

**Comment by leixm** [comment]
> Thanks, could you create a jira ticket for this modify? @leixm

Sure, i updated title.

**Comment by RexXiong** [comment]
Thanks, Merge to main(v0.6.0) and branch-0.5(v0.5.1)

**Pull request closed without merging**
