### PR TITLE
[CELEBORN-1414] PartitionFilesSorter resolve DiskFileInfo without sorting lock

### PR DESCRIPTION
**Pull request by SteNicholas**
### What changes were proposed in this pull request?

`PartitionFilesSorter` calls `resolve` of `DiskFileInfo` without `sorting` lock to reduce the lock scope for performance improvement of `getSortedFileInfo`.

### Why are the changes needed?

`PartitionFilesSorter#resolve` is thread safe. Therefore, `PartitionFilesSorter` invokes `resolve` with `sorting` lock at present, which does not need to lock the resolving of `DiskFileInfo`. `PartitionFilesSorter` could resolve `DiskFileInfo` without `sorting` lock to improve performance of `getSortedFileInfo`.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

GA.

### CODE REVIEW

**Comment by SteNicholas** [comment]
Ping @FMX, @pan3793.

**Comment by SteNicholas** [comment]
Ping @FMX, @cfmcgrady.

**Review by RexXiong — APPROVED** [review]
LGTM, thanks!

**Review by AngersZhuuuu — APPROVED** [review]
LGTM

**Comment by SteNicholas** [comment]
Merging to main(v0.5.0).

**Pull request closed without merging**
