### PR TITLE
[CELEBORN-1318][FOLLOWUP] Upload the celeborn-common to nexus staging for http authentication extensions 

### PR DESCRIPTION
**Pull request by turboFei**
### What changes were proposed in this pull request?
Since https://github.com/apache/celeborn/pull/2440, http authentication is supported.

In this pr, we deploy the `celeborn-common` so that users can leverage the SDK for http authentication extensions. 

### Why are the changes needed?

For http authentication extensions in users end.

### Does this PR introduce _any_ user-facing change?

No, just deploy the `celeborn-common` dependency.

### How was this patch tested?
Run the command locally.

### CODE REVIEW

**Review by cxzl25 — APPROVED** [review]

**Review by cfmcgrady — APPROVED** [review]

**Comment by turboFei** [comment]
thanks, merged to main/0.6

**Comment by pan3793** [comment]
we are continuously adding user extendable interface in different modules, this will eventually result in to publish every modules, I'm wondering if we can create a dedicated module `celeborn-spi` to centralize all extendable interfaces? aslo every interfaces should be annoted with `@since`

**Comment by mridulm** [comment]
+1 to an spi module.
Ideally, keep dependencies for that module minimal as well (so that clients and server side can depend on the same)

**Comment by turboFei** [comment]
raised patch: https://github.com/apache/celeborn/pull/2644

**Pull request closed without merging**
