### PR TITLE
[CELEBORN-1406] Use Files. getLastModifiedTime to find last modified time instead of file.lastModified

### PR DESCRIPTION
**Pull request by mridulm**
### What changes were proposed in this pull request?

Use `Files.readAttributes` instead of `File.lastModified`.
`File.lastModified` has been observed to have issues in some of our build boxes - which got addressed when moving to `Files.readAttributes`

### Why are the changes needed?

Make reloading more reliable and fix flakey tests

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Existing unit tests.

### CODE REVIEW

**Comment by mridulm** [comment]
+CC @otterc, @pan3793, @waitinfuture who reviewed #2419

**Comment by mridulm** [comment]
Converted it back to draft to ensure one more validation run is completed.
+CC @rmcyang, can you please recheck #2419 + #2485 fixes the flakiness seen ? Thanks.

**Comment by pan3793** [comment]
Found a relative answer on stackoverflow.

> Java, at least 1.8 appears to be caching file attributes.
> I found that Files.getLastModifiedTime is a solution for this. But it's only available for Java 1.8 or later.

https://stackoverflow.com/questions/20491448/file-lastmodified-function-does-not-give-the-updated-value

can u try Files.getLastModifiedTime?

**Comment by mridulm** [comment]
Thanks @rmcyang  !
Thanks for the suggestion @pan3793,  it is equivalent to what we have here, but is cleaner !

**Comment by rmcyang** [comment]
Thanks for fixing @mridulm, lgtm. Do you want to reflect the latest change in the title and description? It still references to  `Files.readAttributes`.

**Review by otterc — APPROVED** [review]

**Review by pan3793 — APPROVED** [review]
code change lgtm, please update PR desc

**Comment by mridulm** [comment]
Oh my, I updated only the title and missed out on the description @pan3793.

**Comment by mridulm** [comment]
Merged to master

**Pull request closed without merging**
