### PR TITLE
[CELEBORN-1543] Support Flink 1.20

### PR DESCRIPTION
**Pull request by reswqa**
1.20 was the last non-bug-fix release before Flink 2.0, you can found all main upgrade features in this [release note](https://nightlies.apache.org/flink/flink-docs-release-1.20/release-notes/flink-1.20/). I think the most important feature related to Celeborn is we expose some interface to support Flink hybrid shuffle integration with Celeborn([FLIP-459](https://cwiki.apache.org/confluence/display/FLINK/FLIP-459%3A+Support+Flink+hybrid+shuffle+integration+with+Apache+Celeborn)). This(supporting hybrid shuffle in Celeborn side) is also a follow-up stuff to this PR.

incompatible changes in 1.20:
- 1.20 use enum `CompressionCodec` instead of `String` to construct `BufferDecompressor` and `BufferCompressor`.
- 1.20 introduce a new method(`notifyPartitionRecoveryStarted`) to `JobShuffleContext` in a non-compatible way.

I've already done the adaptation in this PR.

### CODE REVIEW

**Comment by mridulm** [comment]
+CC @venkata91

**Review by SteNicholas — APPROVED** [review]
LGTM. Thanks for supporting Flink 1.20. Forward to integrate with hybrid shuffle in this version.

**Comment by RexXiong** [comment]
For the Flink 1.20 release, please specify the main upgrade features and any incompatible changes for integrating with Remote shuffle service. Additionally, update the docs/README.md file to include instructions for integrating Celeborn with Flink 1.20.

**Review by RexXiong — APPROVED** [review]
LGTM, thanks, merge to main(v0.6.0)

**Pull request closed without merging**
