### PR TITLE
[CELEBORN-1754][CIP-14] Add exceptions and checking utils to cppClient

### PR DESCRIPTION
**Pull request by HolyLow**
### What changes were proposed in this pull request?
This PR adds exceptions and checking utils code to CppClient.
Besides, the ctest framework is added to CppClient for UTs.

### Why are the changes needed?
To provide exception utils and UT frmework to CppClient.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Compilation and UTs.

### CODE REVIEW

**Comment by HolyLow** [comment]
@FMX Could you kindly help review this PR? Thanks a lot.
Besides the exceptions and checking logic, the UT framework is supported now, so the uts are added.

Also note that the prebuild dev image is updated to holylow/celeborn-cpp-dev:0.2 to add gtest module dependency.

Any suggestion is welcome.

**Comment by FMX** [comment]
Copy that. I'll review this PR within this week.

**Comment by FMX** [comment]
@HolyLow I found out that I can run the UTs successfully.

If I run the UTs in Clion, I got following error.
```
1: Test command: /tmp/cpp/cmake-build-debug/celeborn/utils/tests/celeborn_utils_test
1: Working Directory: /tmp/cpp/cmake-build-debug/celeborn/utils/tests
1: Test timeout computed to be: 1500
Exception: Illegal
```

If I run the UTs in Docker container, I got following errors.
```
root@82f7ea7a535c:/celeborn/cpp/build# ctest
Test project /celeborn/cpp/build
    Start 1: celeborn_utils_test
1/1 Test #1: celeborn_utils_test ..............***Exception: Illegal  0.02 sec
0% tests passed, 1 tests failed out of 1


Total Test time (real) =   0.04 sec

The following tests FAILED:
	  1 - celeborn_utils_test (ILLEGAL)
Errors while running CTest
Output from these tests are in: /celeborn/cpp/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
root@82f7ea7a535c:/celeborn/cpp/build# cat /celeborn/cpp/build/Testing/Temporary/LastTest.log
Start testing: Dec 04 02:55 UTC
----------------------------------------------------------
1/1 Testing: celeborn_utils_test
1/1 Test: celeborn_utils_test
Command: "/celeborn/cpp/build/celeborn/utils/tests/celeborn_utils_test"
Directory: /celeborn/cpp/build/celeborn/utils/tests
"celeborn_utils_test" start time: Dec 04 02:55 UTC
Output:
----------------------------------------------------------
<end of output>
Test time =   0.02 sec
----------------------------------------------------------
Test Failed.
"celeborn_utils_test" end time: Dec 04 02:55 UTC
"celeborn_utils_test" time elapsed: 00:00:00
----------------------------------------------------------

End testing: Dec 04 02:55 UTC
```

**Comment by FMX** [comment]
Looks like there is something wrong with the UT, I'll merge this PR after it is fixed.

**Comment by FMX** [comment]
After some investigation, I found the errors that occurred were related to the difference between the arm64 and the x86 platforms. I'll merge this PR. Docker saved the day.

**Review by FMX — APPROVED** [review]
LGTM. Thanks. Merged into main(v0.6.0).

**Pull request closed without merging**
