### PR TITLE
[CELEBORN-1563] Log networkLocation in WorkerInfo

### PR DESCRIPTION
**Pull request by akpatnam25**
### What changes were proposed in this pull request?
Log networkLocation so that it appears during worker registration

### Why are the changes needed?
in the case of custom network location, it would be good to log it

### How was this patch tested?
updated unit tests

### CODE REVIEW

**Comment by akpatnam25** [comment]
cc @mridulm @FMX

**Comment by akpatnam25** [comment]
test failure is unrelated

**Review by FMX — APPROVED** [review]
LGTM.

**Review by SteNicholas — APPROVED** [review]
LGTM.

**Comment by akpatnam25** [comment]
ping, can we merge this? :)

**Comment by akpatnam25** [comment]
ping, can we merge this? :)

**Comment by SteNicholas** [comment]
@akpatnam25, thanks. Merged to main(v0.6.0) and branch-0.5(0.5.2).

**Pull request closed without merging**
