### PR TITLE
[CELEBORN-1745] Remove application top disk usage code

### PR DESCRIPTION
**Pull request by turboFei**
### What changes were proposed in this pull request?
Remove the code for app top disk usage both in master and worker end.

Prefer to use below prometheus expr to figure out the top app usages.
```
topk(50, sum by (applicationId) (metrics_diskBytesWritten_Value{role="worker", applicationId!=""}))
```

### Why are the changes needed?
To address comments: https://github.com/apache/celeborn/pull/2947#issuecomment-2499564978 

> Due to the application dimension resource consumption, this feature should be included in the deprecated features. Maybe you can remove the codes for application top disk usage.

### Does this PR introduce _any_ user-facing change?

Yes, remove the app top disk usage api.

### How was this patch tested?
GA.

### CODE REVIEW

**Comment by SteNicholas** [comment]
@turboFei, this interface should only remove from worker side. The master side does not support application dimension resource consumption.

**Comment by turboFei** [comment]
> @turboFei, this interface should only remove from worker side. The master side does not support application dimension resource consumption.

But currently, the result of master end seems meaningless.

**Comment by SteNicholas** [comment]
@turboFei, IMO, you could only remove the top disk usage code of worker side. The user could use this interface to get the top disk usage of all workers.

**Review by SteNicholas — APPROVED** [review]

**Review by FMX — APPROVED** [review]
LGTM. Thanks. Merged into main(v0.6.0).

**Pull request closed without merging**
