### PR TITLE
[CELEBORN-1553] Using the request base url as swagger server

### PR DESCRIPTION
**Pull request by turboFei**
### What changes were proposed in this pull request?

Using the request base url as swagger server, to prevent the swagger server not reachable and `CORS` error if the swagger server urls do not match. 

Currently, if the http host is bound to local, the swagger server is not reachable.
For example:
```
celeborn.master.http.host=0.0.0.0
celeborn.worker.http.host=0.0.0.0
```

### Why are the changes needed?
image

### Does this PR introduce _any_ user-facing change?

No, just use the request base url as swagger server.

### How was this patch tested?
Integration testing:
image

image

### CODE REVIEW

**Comment by turboFei** [comment]
cc @pan3793

**Comment by turboFei** [comment]
also cc @cfmcgrady @SteNicholas

**Review by RexXiong — APPROVED** [review]
LGTM

**Comment by turboFei** [comment]
Hi @RexXiong 

If no more comments, can we merge it? thanks

**Comment by RexXiong** [comment]
> Hi @RexXiong
> 
> If no more comments, can we merge it? thanks

Thanks for the reminder.

**Pull request closed without merging**
