### PR TITLE
[CELEBORN-1499] Bump Ratis version from 3.0.1 to 3.1.0

### PR DESCRIPTION
**Pull request by SteNicholas**
### What changes were proposed in this pull request?

Bump Ratis version from 3.0.1 to 3.1.0. Meanwhile, remove `CelebornStateMachineStorage` with the release of https://github.com/apache/ratis/pull/1111.

### Why are the changes needed?

Bump Ratis version from 3.0.1 to 3.1.0. Ratis has released v3.1.0, of which release note refers to [3.1.0](https://ratis.apache.org/post/3.1.0.html). The 3.1.0 version is a minor release with multiple improvements and bugfixes including [[RATIS-2111] Reinitialize should load the latest snapshot](https://issues.apache.org/jira/browse/RATIS-2111). See the [changes between 3.0.1 and 3.1.0](https://github.com/apache/ratis/compare/ratis-3.0.1...ratis-3.1.0) releases.

Follow up #2547.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

`MasterStateMachineSuiteJ#testInstallSnapshot`

### CODE REVIEW

**Comment by SteNicholas** [comment]
Ping @AngersZhuuuu, @leixm, @FMX.

**Review by RexXiong — APPROVED** [review]
LGTM

**Comment by FMX** [comment]
I think this PR should test rolling upgrade scenerio.

**Comment by leixm** [comment]
LGTM

**Review by leixm — APPROVED** [review]

**Review by AngersZhuuuu — APPROVED** [review]
LGTM

**Comment by SteNicholas** [comment]
@FMX, I have tested the rolling upgrade scenerio in test environment as follows:
image
image
The result of rolling upgrade is that there is no compatibility problem between the communication of 3.0.1 ratis server and 3.1.0 ratis server.
image
Meanwhile, I have run a test application successfully based on the above situation of master:

**Pull request closed without merging**
