### PR TITLE
[CELEBORN-1528][HELM] Use volumeClaimTemplates to support various storage backend

### PR DESCRIPTION
**Pull request by ChenYi015**
### What changes were proposed in this pull request?

Make helm chart more customizable:
- All master related configurations are prefixed with `master`, e.g. `master.replicas`, `master.volumeClaimTemplates`, `master.volumeMounts`.
- All worker related configurations are prefixed with `worker`, e.g. `worker.replicas`, `worker.nodeSelector`, `worker.affinity`.
- Add support for `labels`, `env`, `envFrom` and `volumeClaimTemplates`.

- Bump chart `appVersion` to `0.5.1`.

### Why are the changes needed?

By using volumeClaimTemplates in StatefulSet, we can support various types of storage backend.

### Does this PR introduce _any_ user-facing change?

Yes.

### How was this patch tested?

Test locally.

### CODE REVIEW

**Comment by ChenYi015** [comment]
@pan3793 @RexXiong PTAL, thanks.

**Comment by ChenYi015** [comment]
To make it can be reviewed and merged easily, I had created a new PR #2654 to do some values renaming. After it has been merged, I will do a rebase.

**Comment by lianneli** [comment]
For my opinion, volumeClaimTemplates is needed but host path and empty path is more general for most of situations. It's better to add it as an option instead of the only choice.

**Comment by ChenYi015** [comment]
If we want to use `volumeClaimTemplates`, suppose `ssd-storage-class` is a valid storage class in your Kubernetes cluster that provided by a cloud provider or defined by yourself that can be used to provide SSD cloud disks dynamically, the configuratio will be like as follows:

```yaml
master:
  volumeClaimTemplates:
  - metadata:
      name: celeborn-ratis
      celeborn.apache.org/disk-type: SSD
      celeborn.apache.org/disk-capacity: 100Gi
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        request:
          storage: 100Gi
        limits:
          storage: 100Gi
      storageClassName: ssd-storage-class
  volumeMounts:
  - name: celeborn-ratis
    mountPath: /mnt/celeborn_ratis

worker:
  volumeClaimTemplates:
  - metadata:
      name: disk1
      annotations:
        celeborn.apache.org/disk-type: SSD
        celeborn.apache.org/disk-capacity: 100Gi
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        request:
          storage: 100Gi
        limits:
          storage: 100Gi
      storageClassName: ssd-storage-class
  volumeMounts:
  - name: disk1
    mountPath: /mnt/disk1
```

The annotations `celeborn.apache.org/disk-type` and `celeborn.apache.org/disk-capacity` are used by Helm to render `celeborn.worker.storage.dirs` in configmap.

**Comment by zemin-piao** [comment]
Hey @ChenYi015 thanks a lot for working on this MR! 

I saw this MR is marked as closed. Could you mention a bit your plan on this MR further? 

Asking this question because we currently are doing similar customisation (using `volumeClaimTemplates`) on the chart internally, and want to align with you so that changes are not far away from each other :D

**Comment by nqvuong1998** [comment]
Hi @ChenYi015 , Do you plan to create a new PR to support volumeClaimTemplates?

**Comment by ChenYi015** [comment]
Yes, I will reopen this or create a new PR recently just after refactoring the Helm chart [CELEBORN-1951](https://issues.apache.org/jira/browse/CELEBORN-1951).

**Pull request closed without merging**
