### PR TITLE
[CELEBORN-1705][0.5][FOLLWUP] Fix cannot find symbol

### PR DESCRIPTION
**Pull request by turboFei**
### What changes were proposed in this pull request?

Fix branch-0.5 build on commit: https://github.com/apache/celeborn/commit/28b2f56e185882a73012f9c8317b5230a69b7188 
### Why are the changes needed?

Fix branch-0.5 build.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

GA

### CODE REVIEW

**Comment by turboFei** [comment]
Hi @FMX， I forced push this fix to branch-0.5, it should be fine?

**Comment by FMX** [comment]
> Hi @FMX， I force pushed this fix to branch-0.5, it should be fine?

The last commit I saw on branch-0.5 is 5c6a2c85. I didn't see any new commit of "[[CELEBORN-1705](https://issues.apache.org/jira/browse/CELEBORN-1705)][0.5][FOLLWUP] Fix cannot find symbol".

**Comment by FMX** [comment]
It's OK but do not do that again. I discovered I solved the cherry-pick conflicts but forgot to compile them before pushing.  I'll compile codes before pushing next time.

**Comment by turboFei** [comment]
ok, thanks for the reminder.

**Pull request closed without merging**
