### PR TITLE
[CELEBORN-1678] Add Celeborn CLI User guide in README

### PR DESCRIPTION
**Pull request by akpatnam25**
### What changes were proposed in this pull request?
adding user guide to README for cli

### Why are the changes needed?
better user experience when using CLI. 

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?
N/A

### CODE REVIEW

**Comment by akpatnam25** [comment]
cc @FMX @SteNicholas

**Comment by SteNicholas** [comment]
Please update `mkdocs.yml` to add navigation for CLI user guide.

**Comment by akpatnam25** [comment]
@SteNicholas  updated

**Review by FMX — APPROVED** [review]
LGTM. Thanks. Merged into main(v0.6.0).

**Pull request closed without merging**
