### PR TITLE
[CELEBORN-1389] Bump Dropwizard version from 3.2.6 to 4.2.25

### PR DESCRIPTION
**Pull request by SteNicholas**
### What changes were proposed in this pull request?

Bump Dropwizard version from 3.2.6 to 4.2.25. Meanwhile, introduce `metrics_jvm_thread_peak_count_Value` and `metrics_jvm_thread_total_started_count_Value` in `celeborn-jvm-dashboard.json`.

### Why are the changes needed?

Dropwizard metrics has released v4.2.25 including some bugfixes and improvements including:

* [JVM] Fix maximum/total memory calculation: https://github.com/dropwizard/metrics/pull/3125
* [Thread] Add peak and total started thread count to `ThreadStatesGaugeSet`: https://github.com/dropwizard/metrics/pull/1601

Meanwhile, Ratis version has upgraded to 3.0.1 which has no compatibility problem with Dropwizard 4.2.25.

Backport:

- https://github.com/apache/spark/pull/26332
- https://github.com/apache/spark/pull/29426
- https://github.com/apache/spark/pull/37372

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Manual test.

### CODE REVIEW

**Comment by SteNicholas** [comment]
Ping @pan3793, @onebox-li.

**Comment by pan3793** [comment]
Have you verified the Grafana Dashboard?

**Comment by SteNicholas** [comment]
@pan3793, I have not verified the dashboard changes. But I just added `metrics_jvm_thread_peak_count_Value` and `metrics_jvm_thread_total_started_count_Value` in dashboard, which works well in theory.

**Review by onebox-li — APPROVED** [review]
Thanks for mention, the grafana dashboard looks fine to me.
image

**Comment by SteNicholas** [comment]
> Thanks for mention, the grafana dashboard looks fine to me.

@pan3793, PTAL.

**Review by FMX — APPROVED** [review]
LGTM. Merge into main(v0.6.0) and branch-0.5.

**Pull request closed without merging**
