### PR TITLE
[CELEBORN-1437][DOC] Merge METRICS.md into monitoring.md

### PR DESCRIPTION
**Pull request by turboFei**
### What changes were proposed in this pull request?

As title, merge these two similar user guides.

### Why are the changes needed?
To close CELEBORN-1437

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Preview https://github.com/turboFei/incubator-celeborn/blob/metrics_merge/docs/monitoring.md#setup-prometheus-dashboard

### CODE REVIEW

**Comment by turboFei** [comment]
cc @RexXiong

**Comment by SteNicholas** [comment]
@turboFei, the main merge should be merging the description of metrics.

**Comment by turboFei** [comment]
>  the main merge should be merging the description of metrics to avoid adding new metric description twice.

Do you mean reserve these two docs at the same time?

**Comment by SteNicholas** [comment]
> > the main merge should be merging the description of metrics to avoid adding new metric description twice.
> 
> Do you mean reserve these two docs at the same time?

I mean that you could move metric table in Metrics.md into monitoring.md to replace origin metric introduction.

**Comment by turboFei** [comment]
> I mean that you could move metric detail table of METRICS.md into monitoring.md to replace origin metric introduction.

Ok, I will recheck it.

**Comment by turboFei** [comment]
I checked the items in METRICS.md one by one.
All the master/worker metrics are included in monitoring.md.

Only these JVM namespace metrics are not mentioned in the monitoring.md

```
             jvm_gc_count              |        JVM        |                                        The GC count of each garbage collector.                                         |
|              jvm_gc_time               |        JVM        |                                      The GC cost time of each garbage collector.                                       |
|          jvm_memory_heap_init          |        JVM        |                                            The amount of heap init memory.                                             |
|          jvm_memory_heap_max           |        JVM        |                                             The amount of heap max memory.                                             |
|          jvm_memory_heap_used          |        JVM        |                                            The amount of heap used memory.                                             |
|       jvm_memory_heap_committed        |        JVM        |                                          The amount of heap committed memory.                                          |
|         jvm_memory_heap_usage          |        JVM        |                                          The percentage of heap memory usage.                                          |
|        jvm_memory_non_heap_init        |        JVM        |                                          The amount of non-heap init memory.                                           |
|        jvm_memory_non_heap_max         |        JVM        |                                           The amount of non-heap max memory.                                           |
|        jvm_memory_non_heap_used        |        JVM        |                                          The amount of non-heap uesd memory.                                           |
|     jvm_memory_non_heap_committed      |        JVM        |                                        The amount of non-heap committed memory.                                        |
|       jvm_memory_non_heap_usage        |        JVM        |                                        The percentage of non-heap memory usage.                                        |
|         jvm_memory_pools_init          |        JVM        |                                     The amount of each memory pool's init memory.                                      |
|          jvm_memory_pools_max          |        JVM        |                                      The amount of each memory pool's max memory.                                      |
|         jvm_memory_pools_used          |        JVM        |                                     The amount of each memory pool's used memory.                                      |
|       jvm_memory_pools_committed       |        JVM        |                                   The amount of each memory pool's committed memory.                                   |
|     jvm_memory_pools_used_after_gc     |        JVM        |                                 The amount of each memory pool's used memory after GC.                                 |
|         jvm_memory_pools_usage         |        JVM        |                                   The percentage of each memory pool's memory usage.                                   |
|         jvm_memory_total_init          |        JVM        |                                            The amount of total init memory.                                            |
|          jvm_memory_total_max          |        JVM        |                                            The amount of total max memory.                                             |
|         jvm_memory_total_used          |        JVM        |                                            The amount of total used memory.                                            |
|       jvm_memory_total_committed       |        JVM        |                                   The amount of each memory pool's committed memory.                                   |
|          jvm_direct_capacity           |        JVM        |                             An estimate of the total capacity of the buffers in this pool                              |
|            jvm_direct_count            |        JVM        |                                    An estimate of the number of buffers in the pool                                    |
|            jvm_direct_used             |        JVM        |                            An estimate of the memory that JVM is using for this buffer pool                            |
|          jvm_mapped_capacity           |        JVM        |                             An estimate of the total capacity of the buffers in this pool                              |
|            jvm_mapped_count            |        JVM        |                                    An estimate of the number of buffers in the pool                                    |
|            jvm_mapped_used             |        JVM        |                            An estimate of the memory that JVM is using for this buffer pool                            |
|            jvm_thread_count            |        JVM        |                                             The current number of threads.                                             |
|        jvm_thread_daemon_count         |        JVM        |                                         The current number of daemon threads.                                          |
|        jvm_thread_blocked_count        |        JVM        |                                  The current number of threads having blocked state.                                   |
|       jvm_thread_deadlock_count        |        JVM        |                                  The current number of threads having deadlock state.                                  |
|          jvm_thread_new_count          |        JVM        |                                    The current number of threads having new state.                                     |
|         jvm_thread_peak_count          |        JVM        |                                        The current number of peak live threads.                                        |
|       jvm_thread_runnable_count        |        JVM        |                                  The current number of threads having runnable state.                                  |
|      jvm_thread_terminated_count       |        JVM        |                                 The current number of threads having terminated state.                                 |
|     jvm_thread_timed_waiting_count     |        JVM        |                               The current number of threads having timed_waiting state.                                |
|     jvm_thread_total_started_count     |        JVM        |                                         The current number of started threads.                                         |
|        jvm_thread_waiting_count        |        JVM        |                                  The current number of threads having waiting state.                                   |
|         jvm_classloader_loaded         |        JVM        |                             The total number of classes loaded since the start of the JVM.                             |
|        jvm_classloader_unloaded        |        JVM        |                            The total number of classes unloaded since the start of the JVM.   
```

But there is some description for such JVM namespace metrics:
image

So, I think all the items are included in monitoring.md.

**Comment by turboFei** [comment]
got it, just merge the description, thanks

**Comment by turboFei** [comment]
> I mean that you could move metric detail table of METRICS.md into monitoring.md to replace origin metric introduction.

Addressed.

**Review by pan3793 — APPROVED** [review]

**Review by cxzl25 — APPROVED** [review]

**Comment by SteNicholas** [comment]
@turboFei, could the metrics in `monitoring.md` be orgainzed in table?

**Comment by turboFei** [comment]
> could the metrics in monitoring.md be organized in table?

I tried to use table, but now for some items shown below, there is not description so far.

```
 - push_server_usedHeapMemory 
    - push_server_usedDirectMemory
    - push_server_numAllocations 
    - push_server_numTinyAllocations
    - push_server_numSmallAllocations
    - push_server_numNormalAllocations
    - push_server_numHugeAllocations
    - push_server_numDeallocations
    - push_server_numTinyDeallocations
    - push_server_numSmallDeallocations
    - push_server_numNormalDeallocations
    - push_server_numHugeDeallocations
    - push_server_numActiveAllocations
    - push_server_numActiveTinyAllocations
    - push_server_numActiveSmallAllocations
    - push_server_numActiveNormalAllocations
    - push_server_numActiveHugeAllocations
    - push_server_numActiveBytes
    - replicate_server_usedHeapMemory
    - replicate_server_usedDirectMemory
    - replicate_server_numAllocations 
    - replicate_server_numTinyAllocations
    - replicate_server_numSmallAllocations
    - replicate_server_numNormalAllocations
    - replicate_server_numHugeAllocations
    - replicate_server_numDeallocations
    - replicate_server_numTinyDeallocations
    - replicate_server_numSmallDeallocations
    - replicate_server_numNormalDeallocations
    - replicate_server_numHugeDeallocations
    - replicate_server_numActiveAllocations
    - replicate_server_numActiveTinyAllocations
    - replicate_server_numActiveSmallAllocations
    - replicate_server_numActiveNormalAllocations
    - replicate_server_numActiveHugeAllocations
    - replicate_server_numActiveBytes
    - fetch_server_usedHeapMemory
    - fetch_server_usedDirectMemory
    - fetch_server_numAllocations 
    - fetch_server_numTinyAllocations
    - fetch_server_numSmallAllocations
    - fetch_server_numNormalAllocations
    - fetch_server_numHugeAllocations
    - fetch_server_numDeallocations
    - fetch_server_numTinyDeallocations
    - fetch_server_numSmallDeallocations
    - fetch_server_numNormalDeallocations
    - fetch_server_numHugeDeallocations
    - fetch_server_numActiveAllocations
    - fetch_server_numActiveTinyAllocations
    - fetch_server_numActiveSmallAllocations
    - fetch_server_numActiveNormalAllocations
    - fetch_server_numActiveHugeAllocations
    - fetch_server_numActiveBytes
```

Can we followup it in another PR, add description for all items and organize them in table?

**Comment by turboFei** [comment]
cc @SteNicholas I have re-organize the metrics with table.

**Review by SteNicholas — APPROVED** [review]

**Comment by SteNicholas** [comment]
Merged to main(v0.6.0).

**Comment by turboFei** [comment]
thanks @SteNicholas  @cxzl25 @pan3793

**Pull request closed without merging**
