### PR TITLE
[Test] test with fine grained pr reverted

### PR DESCRIPTION
**Pull request by YutingWang98**
### What changes were proposed in this pull request?
This is the version used for testing without any fined grained changes, and would expect no data loss. However. there are some jobs still lost a few records during shuffle read
with fine grain change reverted
```
reverted run 1
    Shuffle Write Size / Records: 20.8 TiB / 1965259729
    Shuffle Read Size / Records: 20.8 TiB / 1965259728
reverted run 2
    Shuffle Write Size / Records: 20.8 TiB / 1965259729
    Shuffle Read Size / Records: 20.8 TiB / 1965259729
reverted run 3
    Shuffle Write Size / Records: 20.8 TiB / 1965259729
    Shuffle Read Size / Records: 20.8 TiB / 1965259722
```
Suspect related to 

- [[[CELEBORN-1312](https://issues.apache.org/jira/browse/CELEBORN-1312)] Move handleRequestPartitions out of sync block](https://github.com/apache/celeborn/commit/2456325ff5db6d718e209c5a069f601784ba9314)
- https://github.com/apache/celeborn/pull/2377

Both ^ 2 prs were included in the tests

### CODE REVIEW

**Comment by cfmcgrady** [comment]
> there are some jobs still lost a few records during shuffle read

Could you please provide more details on how to reproduce this bug?

**Comment by waitinfuture** [comment]
https://github.com/apache/celeborn/pull/2621

**Comment by YutingWang98** [comment]
sorry about the late reply @waitinfuture @cfmcgrady, yes, no longer seeing the data loss after applying https://github.com/apache/celeborn/pull/2621, closing this PR

**Comment by waitinfuture** [comment]
Good to know, thanks for verifying! @YutingWang98

**Pull request closed without merging**
