### PR TITLE
[CELEBORN-1360] Ensure that a client cannot push or fetch data belonging to a different application

### PR DESCRIPTION
**Pull request by otterc**
### What changes were proposed in this pull request?
This ensures that an authenticated client is not trying to push or fetch data which belongs to another application.

### Why are the changes needed?
The changes are needed for authentication support.

### Does this PR introduce _any_ user-facing change?
No

### CODE REVIEW

**Comment by otterc** [comment]
@RexXiong @waitinfuture @mridulm @SteNicholas @pan3793 Please take a look

**Review by mridulm — COMMENTED** [review]
The change as such makes sense to me.
My only concern is if the client id is being set will be visible to other threads or not (earlier, it was within the same thread iirc) ... might be a good idea to change it to an AtomicReference ?

**Comment by RexXiong** [comment]
Besides pushing and fetching data, I think we also need to enforce authentication checks for the following RPCs: from LifecycleManager to Worker (ReserveSlots, CommitFiles, DestroyWorkerSlots), and from LifecycleManager to Master (HeartbeatFromApplication, RequestSlots, ApplicationLost, PbUnregisterShuffle, etc.)

**Comment by otterc** [comment]
> My only concern is if the client id is being set will be visible to other threads or not (earlier, it was within the same thread iirc) ... might be a good idea to change it to an AtomicReference ?

@mridulm the client id is being accessed by only one of the event loop which is assigned to the channel. It is not being accessed by different threads. This is similar to how this is done in Spark.

**Comment by otterc** [comment]
> Besides pushing and fetching data, I think we also need to enforce authentication checks for the following RPCs: from LifecycleManager to Worker (ReserveSlots, CommitFiles, DestroyWorkerSlots), and from LifecycleManager to Master (HeartbeatFromApplication, RequestSlots, ApplicationLost, PbUnregisterShuffle, etc.)

@RexXiong This doesn't seem straightforward right now. The Master and Worker use the RPC layer which doesn't exposes the `TransportClient` and the `NettyRpcHandler` doesn't know about appIds in the messages.
My suggestion is that we protect the pushes and fetches right now. I can create a follow-up jira to see how we can check this for these control plane messages.

**Comment by RexXiong** [comment]
> > Besides pushing and fetching data, I think we also need to enforce authentication checks for the following RPCs: from LifecycleManager to Worker (ReserveSlots, CommitFiles, DestroyWorkerSlots), and from LifecycleManager to Master (HeartbeatFromApplication, RequestSlots, ApplicationLost, PbUnregisterShuffle, etc.)
> 
> @RexXiong This doesn't seem straightforward right now. The Master and Worker use the RPC layer which doesn't exposes the `TransportClient` or the `channel` and the `NettyRpcHandler` doesn't know about appIds in the messages. My suggestion is that we protect the data, that is, pushes and fetches right now. I can create a follow-up jira to see how we can check this for these control plane messages.

Make sense to address this in a follow-up JIRA. Additionally, concerning the issue of the RPC layer not exposing the client, I suggest adding TransportClient into NettyRpcCallContext

**Comment by otterc** [comment]
@RexXiong @mridulm Please let me know if you have any other concerns

**Comment by mridulm** [comment]
Looks good to me.

**Review by RexXiong — APPROVED** [review]
Sorry for late reply, LGTM, Thanks!

**Comment by RexXiong** [comment]
Merge to main(v0.5.0)

**Pull request closed without merging**
