### PR TITLE
[CELEBORN-1740][CIP-14] Add stackTrace utils to cppClient

### PR DESCRIPTION
**Pull request by HolyLow**
### What changes were proposed in this pull request?
This PR adds StackTrace utils code to CppClient.

### Why are the changes needed?
To provide StackTrace utils.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Compilation.

### CODE REVIEW

**Comment by HolyLow** [comment]
@FMX Could you kindly review this PR? Thanks a lot.

**Comment by FMX** [comment]
Can you add some unit tests for this PR?

**Comment by FMX** [comment]
> @FMX It is hard to add uts to StackTrace util code along, as it is the building block for Exception utils in later commits. We separate the util codes to avoid large commits though this brings test issues.
> 
> We could add uts when the exception utils are ready, what do you think?

That sounds great to me.

**Review by FMX — APPROVED** [review]
LGTM. Thanks. Merged into main(v0.6.0).

**Pull request closed without merging**
