### PR TITLE
[CELEBORN-1663] Only register appShuffleDeterminate if stage using celeborn for shuffle

### PR DESCRIPTION
**Pull request by s0nskar**
### What changes were proposed in this pull request?
Only register appShuffleDeterminate if stage using celeborn for shuffle

### Why are the changes needed?

Currently we are passing stage info to lifecyclemanager, eventhough it is not required.

### Does this PR introduce _any_ user-facing change?
NA

### How was this patch tested?
Existing UTs

### CODE REVIEW

**Review by zaynt4606 — APPROVED** [review]
LGTM

**Review by RexXiong — APPROVED** [review]
LGTM

**Comment by RexXiong** [comment]
Thanks, but also should modify spark-2 @s0nskar

**Comment by s0nskar** [comment]
Thanks @zaynt4606 @RexXiong for the review. Raised the followup PR for spark 2 - https://github.com/apache/celeborn/pull/2837

**Pull request closed without merging**
