### PR TITLE
[CELEBORN-1534] Order the API v1 response sequences filed

### PR DESCRIPTION
**Pull request by turboFei**
### What changes were proposed in this pull request?
Make the results returned by the API v1 in order.

### Why are the changes needed?

For customer interface friendly. 

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Not needed.

### CODE REVIEW

**Review by RexXiong — APPROVED** [review]
LGTM

**Comment by pan3793** [comment]
it might be costly for sorting shuffle_id and application_id listing API, cc @AngersZhuuuu

**Comment by turboFei** [comment]
> it might be costly for sorting shuffle_id and application_id listing API
If that, I can remove the order for them

**Comment by turboFei** [comment]
maybe we can sort the response in client side.

Waiting for the celeborn-CLI.

**Comment by RexXiong** [comment]
> it might be costly for sorting shuffle_id and application_id listing API, cc @AngersZhuuuu

Perhaps we could add an option to choose between sorted and unsorted results?

**Pull request closed without merging**
