### PR TITLE
[CELEBORN-1521][FOLLOWUP] Move BasicPrincipal to spi module

### PR DESCRIPTION
**Pull request by turboFei**
### What changes were proposed in this pull request?

This PS is a followup of CELEBORN-1521, move the BasicPrincipal in to celeborn-spi module. so that customer do not need to implement it by themselves. 
### Why are the changes needed?

For authentication extension.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?

Existing GA.

### CODE REVIEW

**Comment by pan3793** [comment]
> move the BasicPrincipal in to [celeborn-spi](https://issues.apache.org/jira/browse/CELEBORN-spi) module

I'm not against this, but does it have benefits?

> remove the constructor with `CelebornConf` in `HttpAuthenticationFactory` as `CelebornConf` is in [celeborn-common](https://issues.apache.org/jira/browse/CELEBORN-common) module and not deployed for developer.

I would keep this, the developer still has the option to write custom plugins in their forked celeborn repo

**Comment by turboFei** [comment]
>> move the BasicPrincipal in to [celeborn-spi](https://issues.apache.org/jira/browse/CELEBORN-spi) module

> I'm not against this, but does it have benefits?

The only benefit is that, customer do not need to implement java.security.Principal by them, that is all

**Comment by pan3793** [comment]
> The only benefit is that, customer do not need to implement java.security.Principal by them, that is all

sounds reasonable

**Review by pan3793 — APPROVED** [review]

**Comment by pan3793** [comment]
Merged to main

**Pull request closed without merging**
