### PR TITLE
[CELEBORN-1761][CIP-14] Add cppProto to cppClient

### PR DESCRIPTION
**Pull request by HolyLow**
### What changes were proposed in this pull request?
Add cppProto (TransportMessages.proto, softlinked as TransportMessagesCpp.proto) to cppClient

### Why are the changes needed?
To support proto in cppClient and align with java's definition.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Compilation.

### CODE REVIEW

**Comment by HolyLow** [comment]
@FMX FindProtobuf method has its problem, that the dependency of protobuf-generation cannot be declared explicitly.
This wouldn't be a problem if the protobuf module is exported as a standalone library so the dependency could be solved by other moudle's target_link_library(), but celebornCpp would be exported as a compact library as a whole, and all the compilation target would be exported in a single libceleborn.a.
In this case, the protobuf's .o file would be collected in a libceleborn.a library rather than a standalone libproto.a library, and the dependency between the proto generation and other proto-dependent files cannot be declared by the FindProtobuf method.
This is why I explicitly use the add_custom_command() method which offers more accurate control over the dependency problem. 

Besides, it seems you are using the clion IDE to import the project, and I guess maybe you trigger the compilation by running the utils/tests/ExceptionTest.cpp. 
As the testcase has no dependency over the libproto.a, the proto generation would not be triggered.
If you are running the compilation on command line, like 
```
rm -rf build && mkdir build && cd build
cmake ..
make
```
The libproto.a and the protofiles would be generated as expected, which I've tested several times.

Also, maybe you could try to compile the whole project on Clion IDE to check if the protofile and libproto.a could be generated as expected.

**Comment by HolyLow** [comment]
@FMX It suddenly occurs to me that you could check if your cpp/celeborn/proto/TransportMessagesCpp.proto is valid or not.
As the file is a softlink to java end's TransportMessages.proto, it is possible that the softlink is not working on MacOS environment.
If the softlink is not working, try reclone the project with option `--config core.symlinks=true` to enforce the softlink.
The clone command would be 
```
git clone git@github.com:apache/celeborn.git --config core.symlinks=true
```

**Comment by FMX** [comment]
After some more tests, the build failure is related to the CLION remote development. Building the Celeborn native SDK in the docker container is fine.

**Review by FMX — APPROVED** [review]
LGTM. Merged into main(v0.6.0).

**Pull request closed without merging**
